### ISSUE TITLE
change labeling of assignments to part-1 and part-2

### ISSUE THREAD

**Issue by yentyu** [CU-Denver-UQ/Math1376#28]
This probably doesn't matter too much, but if you are posting the whole module, I'd change the assignment labels to "part-1" and "part-2" because having the assignments as "a" and "b" makes it seem as though you are supposed to do assignment a after doing lecture a and assignment b after lecture b...

But you actually want them to do assignment part a after lecture a & b (i.e., after the first week's modules).

This renaming convention is probably useful for all subsequent modules as well.

**Comment by yentyu** [comment]
(maybe I'm wrong about this though...)

**Comment by eecsu** [comment]
Assignments are going to be released on a weekly schedule instead of "all at once" with the rest of the module. This repo is not quite indicative of the repo I will make for the students that will have materials added on a different schedule (modules all at once in terms of the lecture notebook contents, but assignments in separate directories that are added the week they are assigned, which is two weeks before they are due). Right now, I am developing this all together, so it is easier for me to keep them in the same directories. You bring up a good point though. 

If assignments are also in a separate directory, then I think I would name them like this:

"01-assignment"

"02-parts-a-and-b-assignment" and "02-parts-c-and-d-assignment"

etc. 

What do you think of that?

**Comment by yentyu** [comment]
A little wordy, but I think it makes it much more clear which things go where.
